spring.application.name=cias-personas

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3307/cqcias}
spring.datasource.username=${DB_USER:cqcias}
spring.datasource.password=${DB_PASSWORD:cqcias}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

spring.sql.init.mode=always
